# Site Settings
title: 'Hotel dos Nobres'
tagline: 'Hotel em Poços de Caldas - MG'
url: 'https://hoteldosnobres.com.br'
logo: "https://hoteldosnobres.com.br/imagens/logo.png" # your photo (or logo) here
description: O Hotel dos Nobres está no Centro de Poços de Caldas, oferecemos Quarto de Casal, com duas cama de solteiro ou uma cama de casal e uma de solteiro.Ideal para familia ou vindo a trabalho.​Estamos perto do Cristo Redentor e das Thermas Antônio Carlos. Localizado a cerca de 400 metros da Praça Pedro Sanches, o hotel também fica a 500 metros do Parque Dr. Afonso Junqueira.A propriedade fica a 600 metros do Cassino Palace.​Venha hospedar conosco! ou on-line, WhatsApp (19)97156-4256
image: https://hoteldosnobres.com.br/imagens/logo.png
defaults:
  - scope:
      path: ""
    values:
      image:  'https://hoteldosnobres.com.br/imagens/logo.png'

#Colo Padrao
color: D2154E #55A3BA - #381864

locale: pt_BR #en_US
canonical_url: 'https://hoteldosnobres.com.br/'  
timezone:  America/Sao_Paulo
include: [".well-known"]


author:
  name: 'Hotel dos Nobres'
  url: https://hoteldosnobres.com.br/

  
instagram: hoteldosnobres
social:
  name: hoteldosnobres
  links:
    - https://instagram.com/hoteldosnobres 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Tracker
analytics: G-SREG6HMQW9
adsgoogle: UA-77041161-1
metapixel: 120428271942570
      
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false

